### ISSUE TITLE
Dockerfile publishable

### ISSUE THREAD

**Issue by almereyda** [tom19960222/Dockerfile-hackpad#1]
Hi @tom19960222 ,

I've just read your instructions at https://hub.docker.com/r/tom19960222/hackpad/ and would like to take a look at your Dockerfile.
Do you imagine you can publish it? Else I wouldn't trust your build too much (but will try it, apparently).

Thanks for the effort.

**Comment by tom19960222** [comment]
Hi @almereyda , 
I've pushed my Dockerfile, if you have any question or advise, please let me know. It's my first Dockerfile published on Internet :).
The mysql-connector-java-3.1.14-bin.jar is downloaded from http://dev.mysql.com/downloads/connector/j/3.1.html , if you don't trust it, you can download from official website and replace it.

**Comment by almereyda** [comment]
I will give it another try the next days. It seems when I tried the `docker-compose` file (please also commit + push) from https://hub.docker.com/r/tom19960222/hackpad/, the Hackpad container couldn't connect to the MySQL database. I believe you are inserting the connector to get this working?

I believe there is fair interest in it out there.

**Comment by tom19960222** [comment]
I have put my docker-compose link in readme.md, give it a try :)

**Comment by almereyda** [comment]
Unfortunately it doesn't help me.
I still end up with

```
web_1   | Using mysql database type.
web_1   | Startup execution failed with non-200 response: 500
web_1   | net.appjet.bodylock.JSRuntimeException: Error while executing: Communications link failure due to underlying exception: 
web_1   | 
web_1   | ** BEGIN NESTED EXCEPTION ** 
web_1   | 
web_1   | java.net.SocketException
web_1   | MESSAGE: java.net.NoRouteToHostException: No route to host
```

after running `docker-compose up` with the following test settings:

```
web:
  image: tom19960222/hackpad:latest
  ports:
    - 9000:9000
  environment:
    - HACKPAD_MYSQL_USER=hackpad
    - HACKPAD_MYSQL_PASSWORD=hackpad
    - HACKPAD_MYSQL_HOST=mysql
    - HACKPAD_TOPDOMAINS=localhost
  links:
    - mysql:mysql

mysql:
  image: tutum/mysql:5.5
  environment:
    - MYSQL_USER=hackpad
    - MYSQL_PASS=hackpad
    - ON_CREATE_DB=hackpad
```

Any ideas?
